apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-spring
  name: app-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-spring
  strategy: {}
  template:
    metadata:
      labels:
        app: app-spring
    spec:
      containers:
        - image: localhost:5000/springimage
          name: app-spring
          resources: {}

status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-service
  name: spring-service
spec:
  type: LoadBalancer
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app-spring

---

