apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-mysql-tool
  labels:
    app: app-mysql-tool
spec:
  replicas: 1
  selector:

    matchLabels:
      app: app-mysql-tool
  template:
    metadata:
      labels:
        app: app-mysql-tool
    spec:
      containers:
      - name: app-mysql-tool
        image: mysql:latest
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: cache-volume
        resources: {}

        ports:
        - containerPort: 3306

        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: root
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: mysql-pv-claim-tool

   
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-tool
spec:
  selector:
   
    app: app-mysql-tool
  ports:
  - port: 3306
    targetPort: 3306
    
---
apiVersion: v1
kind: Service
metadata:
  name:  phpmyadmin-sevice-tool
spec:  
  type: LoadBalancer    
  selector:
    app:  app-tool-phpmyadmin
  ports:
  - port: 8001
    targetPort: 80
  
    


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-tool
  labels:
    app: app-mysql-tool
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
