apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-spring
  name: app-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-spring
  strategy: {}
  template:
    metadata:
      labels:
        app: app-spring
    spec:
      containers:
      - image: georgos987/springimage
        name: app-spring
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-service
  name: spring-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.246.87.127
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-spring

---

